// src/theFooter/index.tsx
import GitHubIcon from "~/assets/icons/github-icon.svg";
import TelegramIcon from "~/assets/icons/telegram-icon.svg";
import DiscordIcon from "~/assets/icons/discord-icon.svg";
import MailIcon from "~/assets/icons/mail-icon.svg";
import MastodonIcon from "~/assets/icons/mastodon-icon.svg";
import BSkyIcon from "~/assets/icons/bluesky-icon.png";

export const Component = () => {
  return (
    <footer>
      <span>Find me here:</span>
      <nav>
        <ul>
          <li>
            <a href="https://github.com/drafolin" target="_blank">
              <img width="70" src={GitHubIcon} alt="My github page" />
            </a>
          </li>
          <li>
            <a href="https://t.me/drafolin" target="_blank">
              <img width="70" src={TelegramIcon} alt="My telegram account" />
            </a>
          </li>
          <li>
            <a
              href="https://discordapp.com/users/373515998000840714"
              target="_blank"
            >
              <img width="70" src={DiscordIcon} alt="My discord profile" />
            </a>
          </li>
          <li>
            <a href="mailto:derg@drafolin.ch">
              <img width="70" src={MailIcon} alt="Email me!" />
            </a>
          </li>
          <li>
            <a rel="me" href="https://derg.social/@drafolin" target="_blank">
              <img width="70" src={MastodonIcon} alt="My fediverse account" />
            </a>
          </li>
          <li>
            <a href="https://bsky.app/profile/drafolin.ch" target="_blank">
              <img src={BSkyIcon} alt="My bluesky account!" />
            </a>
          </li>
        </ul>
      </nav>
      <span>
        This site is a work in progress! Some pages might not be existing for
        now...
      </span>
      <br />
      <span>
        <a href="mailto:derg@drafolin.ch">&copy;2021-2023 - Dråfølin</a>
      </span>
    </footer>
  );
};

export default Component;

// dindin/components/TheFooter.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

const messages = {
	en: {
		footer: {
			find: "Find me on",
		}
	},
	fr: {
		footer: {
			find: "Trouve-moi sur",
		}
	}
}
const i18n = useI18n({ messages });
const { t } = i18n;

</script>

<template>
	<footer class="flex flex-col pt-4 px-4 items-center">
		<span>{{ t("footer.find") }}</span>
		<nav class="max-w-xl w-full self-center">
			<ul class="social flex justify-evenly list-none m-2 p-0 w-full">
				<li class="inline m-2 github"><a href="https://github.com/dindin-nibnib">
						<img src="../assets/icons/github-icon.png"
							class="max-w-xs max-h-xs w-full grayscale hover:grayscale-0 transition-all"
							alt="My github page">
					</a></li>
				<li class="inline m-2 twitter"><a href="https://twitter.com/dindin_nibnib">
						<img src="../assets/icons/twitter-icon.png"
							class="max-w-xs max-h-xs w-full grayscale hover:grayscale-0 transition-all"
							alt="My twitter page">
					</a></li>
				<li class="inline m-2 telegram"><a href="https://t.me/dindin_nibnib">
						<img src="../assets/icons/telegram-icon.png"
							class="max-w-xs max-h-xs w-full grayscale hover:grayscale-0 transition-all"
							alt="My telegram account">
					</a></li>
				<li class="inline m-2 discord"><a href="https://discordapp.com/users/373515998000840714">
						<img src="../assets/icons/discord-icon.png"
							class="max-w-xs max-h-xs w-full grayscale hover:grayscale-0 transition-all"
							alt="My discord profile">
					</a></li>
				<li class="inline m-2 mail"><a href="mailto:odinbeuchat.ob@ikmail.com">
						<img src="../assets/icons/mail-icon.png"
							class="max-w-xs max-h-xs w-full grayscale hover:grayscale-0 transition-all" alt="Email me!">
					</a></li>
			</ul>
		</nav>
		<span class="dark:text-gray-400 text-xs lg:text-sm self-center mt-4">This site is a work in progress! Some pages
			might not be existing for now...</span><br />
		<span class="dark:text-gray-400 text-xs lg:text-sm self-center mt-4">
			©2021-2022 - Odin Beuchat | <a href="mailto:odinbeuchat.ob@icloud.com">odinbeuchat.ob@icloud.com</a>
		</span>
	</footer>
</template>
